# Generated by Django 5.2.3 on 2025-07-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='contact',
            name='lastname',
            field=models.CharField(default='lastname', max_length=100),
            preserve_default=False,
        ),
    ]
