# Generated by Django 5.2.3 on 2025-07-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_name_contact_firstname_contact_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
    ]
