# Generated by Django 5.2.3 on 2025-07-17 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_company_notes_contact_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('expectedclosedate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('notes', models.TextField()),
                ('status', models.CharField(choices=[('opportunity', '1-Opportunity'), ('qualification', '2-Qualification'), ('negotiation', '3-Negotiation'), ('closed', 'Closed (Won)'), ('Lost', 'Closed (Lost)')], default='opportunity', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company')),
            ],
        ),
    ]
